import streamlit as st
from datetime import datetime
from typing import List, Dict
from decimal import Decimal
from uuid import uuid4, UUID
from src.crud import SupplierManager, PurchaseRequestManager
from src.models import PurchaseRequest, PurchaseRequestItem

class PROFInterface:
    def __init__(self):
        self.supplier_manager = SupplierManager()
        self.pr_manager = PurchaseRequestManager()
        
    def _get_suppliers(self):
        return self.supplier_manager.get_suppliers()
        
    def _get_item_count(self) -> int:
        if 'item_count' not in st.session_state:
            st.session_state.item_count = 1
        return st.session_state.item_count
        
    def _increase_items(self):
        st.session_state.item_count += 1
        
    def _decrease_items(self):
        if st.session_state.item_count > 1:
            st.session_state.item_count -= 1
    
    def _handle_prof_submission(
        self,
        requestor: str,
        department: str,
        date: datetime,
        urgency: str,
        supplier: Dict,
        items: List[Dict]
    ) -> bool:
        try:
            # Create a temporary UUID for purchase request items
            temp_pr_id = uuid4()
            
            # Create purchase request items
            pr_items = []
            total_amount = Decimal('0')
            
            for item in items:
                quantity = Decimal(str(item['quantity']))
                unit_price = Decimal(str(item['price']))
                total_price = quantity * unit_price
                total_amount += total_price
                
                pr_items.append(PurchaseRequestItem(
                    item_description=item['description'],
                    quantity=quantity,
                    unit=item['unit'],
                    unit_price=unit_price,
                    total_price=total_price,
                    account_code=None,  # We'll add account code functionality later
                    purchase_request_id=temp_pr_id  # Use temporary ID
                ))
            
            # Create purchase request
            purchase_request = PurchaseRequest(
                form_number="",  # Will be generated by the manager
                requestor_id=UUID(st.session_state.user['id']),  # Convert string UUID to UUID object
                supplier_id=UUID(supplier['id']),  # Convert string UUID to UUID object
                status='pending',
                total_amount=total_amount,
                remarks=f"Urgency: {urgency}",
                items=pr_items
            )
            
            # Save to database
            created_pr = self.pr_manager.create_purchase_request(purchase_request)
            
            if created_pr:
                st.success(f"PROF #{created_pr.form_number} created successfully!")
                return True
                
            return False
            
        except Exception as e:
            st.error(f"Error creating PROF: {str(e)}")
            return False
    
    def render(self):
        st.title("Purchase Request and Order Form (PROF)")
        
        # Basic Information
        col1, col2, col3 = st.columns(3)
        with col1:
            requestor = st.text_input("Requestor", value=st.session_state.user['name'], disabled=True)
        with col2:
            department = st.text_input("Department", value=st.session_state.user['role'], disabled=True)
        with col3:
            date = st.date_input("Date", datetime.now())
        
        # Supplier Selection
        suppliers = self._get_suppliers()
        if suppliers:
            supplier_names = {s['name']: s for s in suppliers}
            selected_supplier = st.selectbox("Select Supplier", options=list(supplier_names.keys()))
            supplier = supplier_names[selected_supplier]
        else:
            st.warning("No suppliers found. Please add suppliers first.")
            return
        
        # Urgency
        urgency = st.selectbox("Urgency", ["Normal", "Urgent", "Very Urgent"])
        
        # Items Form
        with st.form("prof_items_form"):
            st.subheader("Items")
            items = []
            
            for i in range(self._get_item_count()):
                st.markdown(f"##### Item {i + 1}")
                col1, col2, col3, col4 = st.columns(4)
                
                with col1:
                    description = st.text_input(f"Description", key=f"desc_{i}")
                with col2:
                    quantity = st.number_input(f"Quantity", min_value=1, value=1, key=f"qty_{i}")
                with col3:
                    unit = st.text_input(f"Unit", key=f"unit_{i}")
                with col4:
                    price = st.number_input(f"Unit Price", min_value=0.0, value=0.0, key=f"price_{i}")
                
                if all([description, quantity, unit, price]):
                    items.append({
                        'description': description,
                        'quantity': quantity,
                        'unit': unit,
                        'price': price
                    })
            
            col1, col2, col3 = st.columns([1, 1, 2])
            with col1:
                if st.form_submit_button("Add Item"):
                    self._increase_items()
                    st.rerun()
            with col2:
                if st.form_submit_button("Remove Item"):
                    self._decrease_items()
                    st.rerun()
            with col3:
                submitted = st.form_submit_button("Submit PROF")
                if submitted:
                    if not items:
                        st.error("Please add at least one item")
                        return
                        
                    success = self._handle_prof_submission(
                        requestor=requestor,
                        department=department,
                        date=date,
                        urgency=urgency,
                        supplier=supplier,
                        items=items
                    )
                    
                    if success:
                        st.session_state.item_count = 1  # Reset form
                        st.rerun()
